[package]
name = "compact_macros"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "Procedural macros for compact arena layouts"
keywords = ["arena", "compact", "macros"]
categories = ["development-tools::procedural-macro-helpers"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "visit-mut"] }
