[workspace]
members = [
    "crates/compact_core",
    "crates/compact_backend_std",
    "crates/compact_collections",
    "crates/compact_serde",
    "crates/compact_frozen",
    "crates/compact_macros",
    "crates/compact_std",
]
resolver = "2"

[workspace.package]
version = "2.3.0"
edition = "2021"
repository = "https://github.com/Biddlebaddleboo/compact-std-library-rust"
rust-version = "1.81"
