//! Packed cage-layout generation.

use proc_macro2::{Span, TokenStream};
use quote::{format_ident, quote};
use syn::parse::Parser;
use syn::punctuated::Punctuated;
use syn::{
    Attribute, Expr, Field, Fields, Ident, ItemEnum, ItemStruct, Meta, Result, Token, Type,
    Visibility,
};

#[derive(Clone, Copy, Eq, PartialEq)]
enum Section {
    Main,
    Hot,
    Cold,
}
enum FieldKind {
    Bool,
    Integer { max: Option<Expr>, signed: bool },
    Enum,
    String,
}
struct FieldSpec {
    ident: Ident,
    ty: Type,
    kind: FieldKind,
    section: Section,
    bits_ident: Ident,
    offset_ident: Ident,
    width_expr: TokenStream,
}

pub(crate) fn expand_struct(attributes: TokenStream, mut item: ItemStruct) -> Result<TokenStream> {
    let soa = parse_compact_args(attributes)?;
    if !item.generics.params.is_empty() || item.generics.where_clause.is_some() {
        return Err(syn::Error::new_spanned(
            &item.generics,
            "generic #[compact] structs are not supported",
        ));
    }
    let Fields::Named(named) = &mut item.fields else {
        return Err(syn::Error::new_spanned(
            &item.fields,
            "#[compact] requires a struct with named fields",
        ));
    };
    let mut specs = Vec::new();
    for field in &mut named.named {
        if field
            .attrs
            .iter()
            .any(|attribute| attribute.path().is_ident("cfg"))
        {
            return Err(syn::Error::new_spanned(
                field,
                "conditional fields are not supported in #[compact] layouts",
            ));
        }
        let (max, section) = field_metadata(field)?;
        let ident = field.ident.clone().expect("named field");
        let kind = classify_field(&field.ty, max, &ident)?;
        let width_expr = match &kind {
            FieldKind::Bool => quote!(1u8),
            FieldKind::Integer {
                max: Some(maximum),
                signed: false,
            } => {
                let ty = &field.ty;
                quote!({ assert!((#maximum as u128) <= (<#ty>::MAX as u128), "#[max] exceeds the field type maximum"); ::compact_std::__private::core::bits_required((#maximum) as u64) })
            }
            FieldKind::Integer { max: None, .. } => {
                let bits = integer_bits(&field.ty).expect("integer field");
                quote!(#bits as u8)
            }
            FieldKind::Enum => {
                let ty = &field.ty;
                quote!(<#ty as ::compact_std::__private::collections::CompactEnum>::BITS)
            }
            FieldKind::String => quote!(0u8),
            FieldKind::Integer {
                signed: true,
                max: Some(_),
            } => unreachable!("signed bounds are rejected"),
        };
        let bits_ident = format_ident!("__COMPACT_{}_BITS", ident.to_string().to_uppercase());
        let offset_ident = format_ident!("{}_BIT_OFFSET", ident.to_string().to_uppercase());
        specs.push(FieldSpec {
            ident,
            ty: field.ty.clone(),
            kind,
            section,
            bits_ident,
            offset_ident,
            width_expr,
        });
    }
    let name = &item.ident;
    let compact_name = format_ident!("{}Compact", name);
    let visibility = &item.vis;
    let constants = layout_constants(&specs);
    let validations = specs.iter().filter_map(constructor_validation);
    let storage_fields = specs.iter().filter_map(|spec| {
        if matches!(spec.kind, FieldKind::String) {
            let field = &spec.ident;
            Some(quote!(#field: ::compact_std::__private::collections::CompactString,))
        } else {
            None
        }
    });
    let string_initializers = specs.iter().filter_map(|spec| {
        if matches!(spec.kind, FieldKind::String) { let field = &spec.ident; Some(quote!(#field: ::compact_std::__private::collections::CompactString::from_str(self.#field.as_str())?,)) } else { None }
    });
    let encoders = specs
        .iter()
        .filter(|spec| !matches!(spec.kind, FieldKind::String))
        .map(|spec| field_encoder(spec, &compact_name));
    let accessors = specs.iter().map(field_accessor);
    let setters = specs.iter().map(field_setter);
    let soa_tokens = if soa {
        generate_soa(name, visibility, &specs)?
    } else {
        TokenStream::new()
    };
    Ok(quote! {
        #item
        #[doc = "Packed cage-backed representation generated by `#[compact]`."]
        #visibility struct #compact_name {
            __compact_main: [u8; #compact_name::MAIN_STORAGE_BYTES],
            __compact_hot: [u8; #compact_name::HOT_STORAGE_BYTES],
            __compact_cold: [u8; #compact_name::COLD_STORAGE_BYTES],
            #(#storage_fields)*
        }
        unsafe impl ::compact_std::__private::core::CompactValue for #compact_name {}
        impl #compact_name { #constants }
        impl #name {
            /// Encode the logical value into its packed compact representation.
            pub fn compact(&self) -> ::compact_std::__private::collections::Result<#compact_name> {
                #(#validations)*
                let mut compact = #compact_name {
                    __compact_main: [0; #compact_name::MAIN_STORAGE_BYTES],
                    __compact_hot: [0; #compact_name::HOT_STORAGE_BYTES],
                    __compact_cold: [0; #compact_name::COLD_STORAGE_BYTES],
                    #(#string_initializers)*
                };
                #(#encoders)*
                Ok(compact)
            }
        }
        impl #compact_name { #(#accessors)* #(#setters)* }
        #soa_tokens
    })
}

pub(crate) fn expand_enum(attributes: TokenStream, item: ItemEnum) -> Result<TokenStream> {
    if !attributes.is_empty() {
        return Err(syn::Error::new(
            Span::call_site(),
            "#[compact] enum does not accept arguments",
        ));
    }
    if !item.generics.params.is_empty() || item.generics.where_clause.is_some() {
        return Err(syn::Error::new_spanned(
            &item.generics,
            "generic #[compact] enums are not supported",
        ));
    }
    for variant in &item.variants {
        if !matches!(variant.fields, Fields::Unit) {
            return Err(syn::Error::new_spanned(
                variant,
                "#[compact] enum supports fieldless variants only",
            ));
        }
    }
    if item.variants.is_empty() {
        return Err(syn::Error::new_spanned(
            &item,
            "#[compact] enum requires at least one variant",
        ));
    }
    let name = &item.ident;
    let compact_name = format_ident!("{}Compact", name);
    let visibility = &item.vis;
    let variants: Vec<_> = item.variants.iter().map(|variant| &variant.ident).collect();
    let maximum = (variants.len() as u64).saturating_sub(1);
    let width = quote!(::compact_std::__private::core::bits_required(#maximum));
    let encoded: Vec<_> = variants
        .iter()
        .enumerate()
        .map(|(index, variant)| {
            let value = index as u64;
            quote!(#name::#variant => #value)
        })
        .collect();
    let decode: Vec<_> = variants
        .iter()
        .enumerate()
        .map(|(index, variant)| {
            let value = index as u64;
            quote!(#value => Ok(#name::#variant))
        })
        .collect();
    let trait_decode: Vec<_> = variants
        .iter()
        .enumerate()
        .map(|(index, variant)| {
            let value = index as u64;
            quote!(#value => Some(#name::#variant))
        })
        .collect();
    let trait_encode: Vec<_> = variants
        .iter()
        .enumerate()
        .map(|(index, variant)| {
            let value = index as u64;
            quote!(#name::#variant => #value)
        })
        .collect();
    let single = variants.len() == 1;
    let get_body = if single {
        let v = variants[0];
        quote!(Ok(#name::#v))
    } else {
        quote! { let value = ::compact_std::__private::core::read_bits(&self.raw, 0, Self::DISCRIMINANT_BITS)?; match value { #(#decode,)* _ => Err(::compact_std::__private::collections::CollectionError::InvalidCompactValue) } }
    };
    let set_body = if single {
        quote! { let _ = value; Ok(()) }
    } else {
        quote! { let encoded = match value { #(#encoded,)* }; ::compact_std::__private::core::write_bits(&mut self.raw, 0, Self::DISCRIMINANT_BITS, encoded)?; Ok(()) }
    };
    let compact_body = if single {
        quote! { let _ = self; Ok(#compact_name { raw: [] }) }
    } else {
        quote! { let encoded = match self { #(#encoded,)* }; let mut compact = #compact_name { raw: [0; #compact_name::STORAGE_BYTES] }; ::compact_std::__private::core::write_bits(&mut compact.raw, 0, #compact_name::DISCRIMINANT_BITS, encoded)?; Ok(compact) }
    };
    Ok(quote! {
        #item
        unsafe impl ::compact_std::__private::core::CompactValue for #name {}
        impl ::compact_std::__private::collections::CompactEnum for #name {
            const BITS: u8 = #width;
            fn compact_bits(&self) -> u64 { match self { #(#trait_encode,)* } }
            fn from_compact_bits(value: u64) -> Option<Self> { match value { #(#trait_decode,)* _ => None } }
        }
        #[doc = "Compact packed discriminant generated by `#[compact]`."]
        #visibility struct #compact_name { raw: [u8; #compact_name::STORAGE_BYTES] }
        unsafe impl ::compact_std::__private::core::CompactValue for #compact_name {}
        impl #compact_name {
            /// Number of bits used by this discriminant.
            pub const DISCRIMINANT_BITS: u8 = #width;
            /// Number of bytes used by this compact discriminant.
            pub const STORAGE_BYTES: usize = (Self::DISCRIMINANT_BITS as usize).div_ceil(8);
            /// Decode this compact discriminant.
            pub fn get(&self) -> ::compact_std::__private::collections::Result<#name> { #get_body }
            /// Replace this discriminant.
            pub fn set(&mut self, value: #name) -> ::compact_std::__private::collections::Result<()> { #set_body }
        }
        impl #name { #[doc = "Encode this variant into a compact discriminant."] pub fn compact(self) -> ::compact_std::__private::collections::Result<#compact_name> { #compact_body } }
    })
}

fn parse_compact_args(attributes: TokenStream) -> Result<bool> {
    let parser = Punctuated::<Ident, Token![,]>::parse_terminated;
    let args = parser.parse2(attributes)?;
    let mut soa = false;
    for argument in args {
        if argument == "soa" && !soa {
            soa = true;
        } else {
            return Err(syn::Error::new_spanned(
                argument,
                "the only supported #[compact(...)] option is `soa`",
            ));
        }
    }
    Ok(soa)
}
fn field_metadata(field: &mut Field) -> Result<(Option<Expr>, Section)> {
    let mut maximum = None;
    let mut section = Section::Main;
    let mut retained = Vec::new();
    for attribute in core::mem::take(&mut field.attrs) {
        if attribute.path().is_ident("max") {
            if maximum.is_some() {
                return Err(syn::Error::new_spanned(attribute, "duplicate #[max] bound"));
            }
            maximum = Some(parse_max(&attribute)?);
        } else if attribute.path().is_ident("hot") {
            if section != Section::Main {
                return Err(syn::Error::new_spanned(
                    attribute,
                    "a field cannot have both #[hot] and #[cold]",
                ));
            }
            section = Section::Hot;
        } else if attribute.path().is_ident("cold") {
            if section != Section::Main {
                return Err(syn::Error::new_spanned(
                    attribute,
                    "a field cannot have both #[hot] and #[cold]",
                ));
            }
            section = Section::Cold;
        } else {
            retained.push(attribute);
        }
    }
    field.attrs = retained;
    Ok((maximum, section))
}
fn parse_max(attribute: &Attribute) -> Result<Expr> {
    match &attribute.meta {
        Meta::NameValue(value) => Ok(value.value.clone()),
        _ => Err(syn::Error::new_spanned(
            attribute,
            "write a field bound as `#[max = CONST_EXPR]`",
        )),
    }
}
fn classify_field(ty: &Type, max: Option<Expr>, field: &Ident) -> Result<FieldKind> {
    let Type::Path(path) = ty else {
        return Err(syn::Error::new_spanned(
            ty,
            "unsupported compact field type",
        ));
    };
    let Some(segment) = path.path.segments.last() else {
        return Err(syn::Error::new_spanned(
            ty,
            "unsupported compact field type",
        ));
    };
    match segment.ident.to_string().as_str() {
        "bool" => {
            if max.is_some() {
                return Err(syn::Error::new_spanned(
                    field,
                    "bool fields do not use #[max]",
                ));
            }
            Ok(FieldKind::Bool)
        }
        "String" => {
            if max.is_some() {
                return Err(syn::Error::new_spanned(
                    field,
                    "String fields do not use #[max]",
                ));
            }
            Ok(FieldKind::String)
        }
        "u8" | "u16" | "u32" | "u64" | "usize" => Ok(FieldKind::Integer { max, signed: false }),
        "i8" | "i16" | "i32" | "i64" | "isize" => {
            if max.is_some() {
                return Err(syn::Error::new_spanned(
                    field,
                    "#[max] currently applies only to unsigned fields",
                ));
            }
            Ok(FieldKind::Integer {
                max: None,
                signed: true,
            })
        }
        _ if max.is_some() => Err(syn::Error::new_spanned(
            field,
            "#[max] requires an unsigned integer field",
        )),
        _ if path
            .path
            .segments
            .iter()
            .all(|segment| matches!(segment.arguments, syn::PathArguments::None)) =>
        {
            Ok(FieldKind::Enum)
        }
        _ => Err(syn::Error::new_spanned(
            ty,
            "unsupported compact field type",
        )),
    }
}
fn integer_bits(ty: &Type) -> Option<TokenStream> {
    let Type::Path(path) = ty else { return None };
    let ident = &path.path.segments.last()?.ident;
    Some(quote!(#ident::BITS))
}
fn layout_constants(specs: &[FieldSpec]) -> TokenStream {
    let widths = specs.iter().map(|spec| {
        let id = &spec.bits_ident;
        let value = &spec.width_expr;
        quote!(#[doc(hidden)] pub const #id: u8 = #value;)
    });
    let offsets = specs.iter().enumerate().map(|(index, spec)| {
        let id = &spec.offset_ident;
        let prior: Vec<_> = specs[..index]
            .iter()
            .filter(|previous| previous.section == spec.section)
            .map(|previous| {
                let bits = &previous.bits_ident;
                quote!(Self::#bits as usize)
            })
            .collect();
        quote!(pub const #id: usize = 0usize #(+ #prior)*;)
    });
    let widths_for = |section| {
        specs
            .iter()
            .filter(|spec| spec.section == section)
            .map(|spec| &spec.bits_ident)
            .collect::<Vec<_>>()
    };
    let main = widths_for(Section::Main);
    let hot = widths_for(Section::Hot);
    let cold = widths_for(Section::Cold);
    let sum = |items: &[&Ident]| quote!(0usize #(+ Self::#items as usize)*);
    let main_bits = sum(&main);
    let hot_bits = sum(&hot);
    let cold_bits = sum(&cold);
    quote! { #(#widths)* #(#offsets)* pub const MAIN_STORAGE_BYTES: usize = (#main_bits).div_ceil(8); pub const HOT_STORAGE_BYTES: usize = (#hot_bits).div_ceil(8); pub const COLD_STORAGE_BYTES: usize = (#cold_bits).div_ceil(8); pub const STORAGE_BYTES: usize = Self::MAIN_STORAGE_BYTES + Self::HOT_STORAGE_BYTES + Self::COLD_STORAGE_BYTES; }
}
fn constructor_validation(spec: &FieldSpec) -> Option<TokenStream> {
    let FieldKind::Integer {
        max: Some(max),
        signed: false,
    } = &spec.kind
    else {
        return None;
    };
    let field = &spec.ident;
    Some(
        quote! { if (self.#field as u64) > ((#max) as u64) { return Err(::compact_std::__private::collections::CollectionError::Core(::compact_std::__private::core::Error::ValueDoesNotFit)); } },
    )
}
fn segment_ident(section: Section) -> Ident {
    Ident::new(
        match section {
            Section::Main => "__compact_main",
            Section::Hot => "__compact_hot",
            Section::Cold => "__compact_cold",
        },
        Span::call_site(),
    )
}
fn field_encoder(spec: &FieldSpec, name: &Ident) -> TokenStream {
    let field = &spec.ident;
    let segment = segment_ident(spec.section);
    let offset = &spec.offset_ident;
    let bits = &spec.bits_ident;
    match &spec.kind {
        FieldKind::Bool => {
            quote!(::compact_std::__private::core::write_bits(&mut compact.#segment, #name::#offset, #name::#bits, self.#field as u64)?;)
        }
        FieldKind::Integer { signed: true, .. } => {
            quote!({ let mut value = self.#field as u64; if #name::#bits < 64 { value &= (1_u64 << #name::#bits) - 1; } ::compact_std::__private::core::write_bits(&mut compact.#segment, #name::#offset, #name::#bits, value)?; })
        }
        FieldKind::Integer {
            max: Some(_),
            signed: false,
        } => {
            quote!(if #name::#bits != 0 { ::compact_std::__private::core::write_bits(&mut compact.#segment, #name::#offset, #name::#bits, self.#field as u64)?; })
        }
        FieldKind::Integer {
            signed: false,
            max: None,
        } => {
            quote!(::compact_std::__private::core::write_bits(&mut compact.#segment, #name::#offset, #name::#bits, self.#field as u64)?;)
        }
        FieldKind::Enum => {
            quote!({ let value = ::compact_std::__private::collections::CompactEnum::compact_bits(&self.#field); if #name::#bits != 0 { ::compact_std::__private::core::write_bits(&mut compact.#segment, #name::#offset, #name::#bits, value)?; } })
        }
        FieldKind::String => TokenStream::new(),
    }
}
fn field_accessor(spec: &FieldSpec) -> TokenStream {
    let field = &spec.ident;
    let ty = &spec.ty;
    let segment = segment_ident(spec.section);
    let offset = &spec.offset_ident;
    let bits = &spec.bits_ident;
    match &spec.kind {
        FieldKind::Bool => {
            quote!(#[doc = "Read this packed boolean."] pub fn #field(&self) -> ::compact_std::__private::collections::Result<bool> { Ok(::compact_std::__private::core::read_bits(&self.#segment, Self::#offset, Self::#bits)? != 0) })
        }
        FieldKind::Integer {
            max: Some(_),
            signed: false,
        } => {
            quote!(#[doc = "Read this packed integer."] pub fn #field(&self) -> ::compact_std::__private::collections::Result<#ty> { let value = if Self::#bits == 0 { 0 } else { ::compact_std::__private::core::read_bits(&self.#segment, Self::#offset, Self::#bits)? }; Ok(value as #ty) })
        }
        FieldKind::Integer { .. } => {
            quote!(#[doc = "Read this packed integer."] pub fn #field(&self) -> ::compact_std::__private::collections::Result<#ty> { Ok(::compact_std::__private::core::read_bits(&self.#segment, Self::#offset, Self::#bits)? as #ty) })
        }
        FieldKind::Enum => {
            quote!(#[doc = "Decode this packed fieldless enum."] pub fn #field(&self) -> ::compact_std::__private::collections::Result<#ty> { let value = if Self::#bits == 0 { 0 } else { ::compact_std::__private::core::read_bits(&self.#segment, Self::#offset, Self::#bits)? }; <#ty as ::compact_std::__private::collections::CompactEnum>::from_compact_bits(value).ok_or(::compact_std::__private::collections::CollectionError::InvalidCompactValue) })
        }
        FieldKind::String => {
            quote!(#[doc = "Borrow the UTF-8 field."] pub fn #field(&self) -> &str { self.#field.as_str() })
        }
    }
}
fn field_setter(spec: &FieldSpec) -> TokenStream {
    let field = &spec.ident;
    let setter = format_ident!("set_{}", field);
    let ty = &spec.ty;
    let segment = segment_ident(spec.section);
    let offset = &spec.offset_ident;
    let bits = &spec.bits_ident;
    match &spec.kind {
        FieldKind::Bool => {
            quote!(#[doc = "Update this boolean."] pub fn #setter(&mut self, value: bool) -> ::compact_std::__private::collections::Result<()> { ::compact_std::__private::core::write_bits(&mut self.#segment, Self::#offset, Self::#bits, value as u64)?; Ok(()) })
        }
        FieldKind::Integer {
            max: Some(max),
            signed: false,
        } => {
            quote!(#[doc = "Update this bounded integer."] pub fn #setter(&mut self, value: #ty) -> ::compact_std::__private::collections::Result<()> { if (value as u64) > ((#max) as u64) { return Err(::compact_std::__private::collections::CollectionError::Core(::compact_std::__private::core::Error::ValueDoesNotFit)); } if Self::#bits != 0 { ::compact_std::__private::core::write_bits(&mut self.#segment, Self::#offset, Self::#bits, value as u64)?; } Ok(()) })
        }
        FieldKind::Integer { signed: true, .. } => {
            quote!(#[doc = "Update this integer."] pub fn #setter(&mut self, value: #ty) -> ::compact_std::__private::collections::Result<()> { let mut encoded = value as u64; if Self::#bits < 64 { encoded &= (1_u64 << Self::#bits) - 1; } ::compact_std::__private::core::write_bits(&mut self.#segment, Self::#offset, Self::#bits, encoded)?; Ok(()) })
        }
        FieldKind::Integer {
            signed: false,
            max: None,
        } => {
            quote!(#[doc = "Update this integer."] pub fn #setter(&mut self, value: #ty) -> ::compact_std::__private::collections::Result<()> { ::compact_std::__private::core::write_bits(&mut self.#segment, Self::#offset, Self::#bits, value as u64)?; Ok(()) })
        }
        FieldKind::Enum => {
            quote!(#[doc = "Update this enum."] pub fn #setter(&mut self, value: #ty) -> ::compact_std::__private::collections::Result<()> { let encoded = ::compact_std::__private::collections::CompactEnum::compact_bits(&value); if Self::#bits != 0 { ::compact_std::__private::core::write_bits(&mut self.#segment, Self::#offset, Self::#bits, encoded)?; } Ok(()) })
        }
        FieldKind::String => {
            quote!(#[doc = "Replace this compact string."] pub fn #setter(&mut self, value: &str) -> ::compact_std::__private::collections::Result<()> { self.#field = ::compact_std::__private::collections::CompactString::from_str(value)?; Ok(()) })
        }
    }
}
fn generate_soa(name: &Ident, visibility: &Visibility, specs: &[FieldSpec]) -> Result<TokenStream> {
    if specs
        .iter()
        .any(|spec| matches!(spec.kind, FieldKind::String | FieldKind::Enum))
    {
        return Err(syn::Error::new_spanned(
            name,
            "#[compact(soa)] supports bool and integer scalar fields",
        ));
    }
    let soa = format_ident!("{}Soa", name);
    let columns = specs.iter().map(|spec| {
        let field = &spec.ident;
        let ty = &spec.ty;
        if matches!(spec.kind, FieldKind::Bool) {
            quote!(#field: ::compact_std::__private::collections::CompactBitVec,)
        } else {
            quote!(#field: ::compact_std::__private::collections::CompactVec<#ty>,)
        }
    });
    let empty = specs.iter().map(|spec| {
        let field = &spec.ident;
        if matches!(spec.kind, FieldKind::Bool) {
            quote!(#field: ::compact_std::__private::collections::CompactBitVec::new(),)
        } else {
            quote!(#field: ::compact_std::__private::collections::CompactVec::new(),)
        }
    });
    let reserved = specs.iter().map(|spec| { let field = &spec.ident; if matches!(spec.kind, FieldKind::Bool) { quote!(#field: ::compact_std::__private::collections::CompactBitVec::with_capacity(capacity)?,) } else { quote!(#field: ::compact_std::__private::collections::CompactVec::with_capacity(capacity)?,) } });
    let reserves = specs.iter().map(|spec| {
        let field = &spec.ident;
        quote!(self.#field.reserve(1)?;)
    });
    let pushes = specs.iter().map(|spec| { let field = &spec.ident; let rollback = specs.iter().map(|column| { let id = &column.ident; quote!(self.#id.truncate(old_len);) }); quote!(if let Err(error) = self.#field.push(value.#field) { #(#rollback)* return Err(error.into()); }) });
    let getters = specs.iter().map(|spec| { let field = &spec.ident; if matches!(spec.kind, FieldKind::Bool) { quote!(#field: self.#field.get(index).ok_or(::compact_std::__private::collections::CollectionError::Core(::compact_std::__private::core::Error::OutOfBounds))?,) } else { quote!(#field: *self.#field.get(index).ok_or(::compact_std::__private::collections::CollectionError::Core(::compact_std::__private::core::Error::OutOfBounds))?,) } });
    Ok(quote! {
        /// Columnar cage collection generated by `#[compact(soa)]`.
        #visibility struct #soa { #(#columns)* len: u32 }
        unsafe impl ::compact_std::__private::core::CompactValue for #soa {}
        impl #soa {
            /// Construct empty compact columns.
            pub fn new() -> Self { Self { #(#empty)* len: 0 } }
            /// Reserve capacity in each column.
            pub fn with_capacity(capacity: usize) -> ::compact_std::__private::collections::Result<Self> { Ok(Self { #(#reserved)* len: 0 }) }
            /// Return record count.
            pub const fn len(&self) -> usize { self.len as usize }
            /// Return whether no records are stored.
            pub const fn is_empty(&self) -> bool { self.len == 0 }
            /// Append a record to every column.
            pub fn push(&mut self, value: #name) -> ::compact_std::__private::collections::Result<()> {
                let old_len = self.len();
                let next_len = old_len.checked_add(1).and_then(|n| u32::try_from(n).ok()).ok_or(::compact_std::__private::collections::CollectionError::CapacityOverflow)?;
                #(#reserves)*
                #(#pushes)*
                self.len = next_len;
                Ok(())
            }
            /// Reconstruct one logical record.
            pub fn get(&self, index: usize) -> ::compact_std::__private::collections::Result<Option<#name>> {
                if index >= self.len() { return Ok(None); }
                Ok(Some(#name { #(#getters)* }))
            }
        }
    })
}
