[package]
name = "compact_collections"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "Compact collections backed by a process-wide cage"
keywords = ["cage", "compact", "collections"]
categories = ["data-structures", "memory-management"]

[dependencies]
compact_backend_std = { path = "../compact_backend_std", version = "2.3.0" }
compact_core = { path = "../compact_core", version = "2.3.0" }

[dev-dependencies]
compact_backend_std = { path = "../compact_backend_std", version = "2.3.0" }
proptest = "=1.6.0"
