//! Deserialize directly into arena-backed compact values.
//!
//! The seed owns the mutable arena borrow for one Serde operation. Visitors
//! allocate compact fields as they are read, so malformed input and arena
//! exhaustion drop any partially constructed owners through their normal drop
//! paths.

#![forbid(unsafe_code)]

mod deserialize;

pub use deserialize::{CompactDeserialize, CompactDeserializeSeed};

#[cfg(feature = "json")]
pub mod json;
#[cfg(feature = "toml")]
pub mod toml;

/// Paths used by code generated by `#[derive(CompactDeserialize)]`.
#[doc(hidden)]
pub mod __private {
    pub use serde;
}
